nome = input('Nome completo:').strip()
maiusculo = nome.upper()
minusculo = nome.lower()
lista = nome.split()
juncao = len(''.join(lista))
print('Analisando seu nome...')
print('Seu nome em maiusculo é {}'.format(maiusculo))
print('Seu nome em minusculo é {}'.format(minusculo))
print('Seu nome ao todo tem {} letras'.format(juncao))
print('Seu primeiro nome é {} e ele tem letras {}'.format(lista[0], len(lista[0])))
